version: 0.0.0
plugins:
  - name: storage
    file: internal
    configs:
      root: data
  - name: cli_interface
    as: interface
    file: internal
    configs:
      chat_prefix: '[backend]: '
#  - name: cq_interface
#    file: internal
#    configs:
#      address: ':6700'
#      groups:
#        - id: 958915720
#          name: Q
#      format: '([src])[user]: [msg]'
  - name: show_game_chat
    as: ''
    file: internal
    require:
      - interface
    configs:
      dests:
        - plugin: storage
          format: '[src]: [msg] ([type])'
        - plugin: interface
          format: '[src]: [msg] ([type])'
#        - plugin: cq_interface
#          format: '[src]: [msg]'
#          filter:
#            - "not me"
#            - "chat only"
      hint: chat
  - name: send_cmd_line
    file: internal
    configs:
      sources:
        - plugin: interface
          reg_name: send_cmd_line
          prefix: /
      log_name: send_solo_cmd_line
      log_plugin: storage